# Generated by Django 5.1.1 on 2024-12-01 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('informatica', '0002_auto_20241130_2344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='docente',
            old_name='updated',
            new_name='actualizado',
        ),
        migrations.RenameField(
            model_name='docente',
            old_name='created',
            new_name='creado',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='updated',
            new_name='actualizado',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='password',
            new_name='contraseña',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='created',
            new_name='creado',
        ),
    ]
