# Generated by Django 5.1.1 on 2024-12-01 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('informatica', '0003_rename_updated_docente_actualizado_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='contraseña',
            new_name='password',
        ),
    ]
